# Generated by Django 3.1.4 on 2021-01-17 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('payee', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('ingoing', models.DecimalField(decimal_places=2, max_digits=7)),
                ('outgoing', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
