# Generated by Django 3.1.4 on 2021-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0005_auto_20210118_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ingoing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outgoing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
