# Generated by Django 3.1.4 on 2021-01-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0011_auto_20210118_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(default='01/19/21'),
        ),
    ]
