# Generated by Django 3.1.4 on 2021-01-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0012_auto_20210118_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateField(default='01/23/21'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ingoing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outgoing',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
